/**
 * The codec vocabularies as first shipped. Codes refer to entries by index, so `vocab.test.ts`
 * checks that the live lists still start with these, and `tables` pins the probability model.
 * When appending to a vocabulary, append here too; never change an existing entry.
 */
export const SNAPSHOT = {
  tables: '362d06428ef95830',
  words: {
    count: 320,
    hash: '83dd553e86ef5ef4',
  },
  phrases: {
    count: 96,
    hash: '3d5015584fc68972',
  },
  boards: [
    'beastmaker-1000',
    'beastmaker-2000',
    'tension-grindstone-mk2',
    'metolius-simulator-3d',
    'metolius-project',
    'metolius-wood-grips-compact',
    'metolius-wood-grips-deluxe',
    'fika-vetelangd',
  ],
  presets: [
    'first-hangs',
    'no-hangs',
    'density-hangs',
    'repeaters-7-3',
    'max-hangs',
    'minimum-edge',
    'two-grip-repeaters',
    'seven-fifty-three',
    'one-arm-hangs',
    'three-grip-max-hangs',
  ],
  grips: {
    'beastmaker-1000': [
      'jug-l+jug-r',
      'sloper-35-l+sloper-35-r',
      'sloper-20',
      'edge-small-l+edge-small-r',
      'pocket-4f-deep-l+pocket-4f-deep-r',
      'edge-large-l+edge-large-r',
      'pocket-2f-deep-l+pocket-2f-deep-r',
      'pocket-3f-deep-l+pocket-3f-deep-r',
      'slot-flat',
      'edge-medium-l+edge-medium-r',
      'pocket-2f-shallow-l+pocket-2f-shallow-r',
      'pocket-3f-shallow-l+pocket-3f-shallow-r',
    ],
    'beastmaker-2000': [
      'sloper-45-l+sloper-45-r',
      'sloper-35-l+sloper-35-r',
      'sloper-20',
      'edge-top-deep-l+edge-top-shallow-r',
      'edge-big-l+edge-big-r',
      'mono-deep-l+mono-deep-r',
      'pocket-2f-big-l+pocket-2f-big-r',
      'pocket-3f-medium-l+pocket-3f-medium-r',
      'pocket-4f-deep',
      'edge-little-l+edge-little-r',
      'mono-1pad-l+mono-1pad-r',
      'pocket-2f-little-l+pocket-2f-sloping-r',
      'pocket-3f-small-l+pocket-3f-small-r',
      'edge-22',
    ],
    'tension-grindstone-mk2': [
      'jug',
      'edge-10-l+edge-10-r',
      'edge-8-l+edge-8-r',
      'edge-30-l+edge-30-r',
      'edge-25-l+edge-25-r',
      'edge-50',
      'edge-20-l+edge-20-r',
      'edge-15-l+edge-15-r',
    ],
    'metolius-simulator-3d': [
      'jug-l+jug-r',
      'sloper-flat-l+sloper-flat-r',
      'sloper-round-l+sloper-round-r',
      'jug-center',
      'pocket-3f-50',
      'pocket-3f-30-l+pocket-3f-30-r',
      'edge-25-l+edge-25-r',
      'edge-19-l+edge-19-r',
      'edge-36-l+edge-36-r',
      'pocket-3f-37',
      'pocket-3f-15-l+pocket-3f-15-r',
      'pocket-3f-35-l+pocket-3f-35-r',
      'pocket-3f-17-l+pocket-3f-17-r',
      'pocket-2f-28',
      'edge-14-l+edge-14-r',
      'pocket-2f-30-l+pocket-2f-30-r',
      'pocket-2f-14-l+pocket-2f-14-r',
      'pocket-2f-32',
    ],
    'metolius-project': [
      'jug-l+jug-r',
      'sloper-flat-l+sloper-flat-r',
      'sloper-round',
      'pocket-3f-45-l+pocket-3f-45-r',
      'edge-30-l+edge-30-r',
      'pocket-2f-40-l+pocket-2f-40-r',
      'edge-39',
      'pocket-3f-22-l+pocket-3f-22-r',
      'pocket-2f-22-l+pocket-2f-22-r',
      'edge-16',
    ],
    'metolius-wood-grips-compact': [
      'jug-l+jug-r',
      'sloper-flat-l+sloper-flat-r',
      'sloper-round',
      'edge-29-l+edge-29-r',
      'pocket-3f-29-l+pocket-3f-29-r',
      'pocket-2f-29-l+pocket-2f-29-r',
      'pocket-4f-29',
      'edge-19-l+edge-19-r',
      'pocket-3f-19-l+pocket-3f-19-r',
      'pocket-2f-19-l+pocket-2f-19-r',
      'pocket-4f-19',
    ],
    'metolius-wood-grips-deluxe': [
      'jug-l+jug-r',
      'sloper-flat-l+sloper-flat-r',
      'sloper-round',
      'edge-31-l+edge-31-r',
      'pocket-3f-32-l+pocket-3f-32-r',
      'pocket-2f-38-l+pocket-2f-38-r',
      'pocket-4f-32',
      'edge-25-l+edge-25-r',
      'pocket-3f-25-l+pocket-3f-25-r',
      'pocket-2f-28-l+pocket-2f-28-r',
      'pocket-4f-25',
      'edge-19-l+edge-19-r',
      'pocket-3f-19-l+pocket-3f-19-r',
      'pocket-2f-19-l+pocket-2f-19-r',
      'pocket-4f-19',
    ],
    'fika-vetelangd': [
      'sloper-25-l+sloper-25-r',
      'sloper-35-l+sloper-35-r',
      'edge-20-l+edge-20-r',
      'edge-25-l+edge-25-r',
      'edge-15-l+edge-15-r',
      'edge-12-l+edge-12-r',
      'hole-30-l+hole-30-r',
      'edge-10-l+edge-10-r',
      'trough',
    ],
  },
} as const;
